-- Seed Data: Certifications
-- Description: Initial certification programs for 100xSystems
-- Version: 1.0.0

INSERT INTO certifications (slug, title, description, roadmap_slug, issuer, difficulty, estimated_hours, requirements, certificate_template_url, badge_url, is_active, sort_order) VALUES
-- Foundation Certifications
('foundation-javascript', 'JavaScript Foundation', 'Master the fundamentals of JavaScript programming including variables, functions, objects, and asynchronous programming', 'foundation-javascript', '100xSystems', 'beginner', 40, '{"articles": ["variables-basics", "functions-deep-dive", "objects-arrays", "async-programming"], "quiz_score": 80, "project": "todo-app"}', '/certificates/templates/foundation-javascript.html', '/certificates/badges/foundation-javascript.svg', true, 1),
('foundation-systems', 'Systems Thinking Foundation', 'Understand core system design principles, database fundamentals, and networking basics', 'foundation-systems', '100xSystems', 'beginner', 60, '{"articles": ["system-design-basics", "database-fundamentals", "networking-basics"], "quiz_score": 75, "project": "simple-api"}', '/certificates/templates/foundation-systems.html', '/certificates/badges/foundation-systems.svg', true, 2),

-- Development Certifications
('frontend-development', 'Frontend Development Mastery', 'Build modern web applications using React, TypeScript, and responsive design principles', 'development-frontend', '100xSystems', 'intermediate', 80, '{"prerequisites": ["foundation-javascript"], "articles": ["html-css-mastery", "react-fundamentals", "typescript-basics", "responsive-design"], "quiz_score": 85, "project": "portfolio-website"}', '/certificates/templates/frontend-development.html', '/certificates/badges/frontend-development.svg', true, 3),
('backend-development', 'Backend Development Mastery', 'Design and build scalable backend APIs using Node.js, Express, and database integration', 'development-backend', '100xSystems', 'intermediate', 80, '{"prerequisites": ["foundation-javascript"], "articles": ["nodejs-fundamentals", "express-api-design", "database-integration", "authentication-basics"], "quiz_score": 85, "project": "rest-api-service"}', '/certificates/templates/backend-development.html', '/certificates/badges/backend-development.svg', true, 4),
('fullstack-development', 'Full-Stack Development', 'Complete end-to-end web development with modern frontend and backend technologies', 'development-fullstack', '100xSystems', 'advanced', 120, '{"prerequisites": ["frontend-development", "backend-development"], "articles": ["fullstack-architecture", "deployment-strategies", "testing-methodologies", "performance-optimization"], "quiz_score": 80, "project": "production-app"}', '/certificates/templates/fullstack-development.html', '/certificates/badges/fullstack-development.svg', true, 5),

-- Systems Certifications
('system-design', 'System Design Fundamentals', 'Learn to design scalable, maintainable systems that handle real-world requirements', 'systems-design', '100xSystems', 'intermediate', 100, '{"prerequisites": ["foundation-systems"], "articles": ["scalability-patterns", "microservices-architecture", "load-balancing", "caching-strategies"], "quiz_score": 85, "project": "distributed-system"}', '/certificates/templates/system-design.html', '/certificates/badges/system-design.svg', true, 6),
('database-design', 'Database Design & Optimization', 'Master database architecture, query optimization, and data modeling for scale', 'systems-database', '100xSystems', 'intermediate', 90, '{"prerequisites": ["foundation-systems"], "articles": ["database-modeling", "query-optimization", "nosql-databases", "data-migration"], "quiz_score": 80, "project": "database-schema"}', '/certificates/templates/database-design.html', '/certificates/badges/database-design.svg', true, 7),
('security-fundamentals', 'Security Fundamentals', 'Implement security best practices and understand common vulnerabilities', 'systems-security', '100xSystems', 'intermediate', 70, '{"prerequisites": ["foundation-systems"], "articles": ["authentication-authorization", "security-best-practices", "common-vulnerabilities", "security-testing"], "quiz_score": 85, "project": "secure-app"}', '/certificates/templates/security-fundamentals.html', '/certificates/badges/security-fundamentals.svg', true, 8),

-- DevOps Certifications
('devops-fundamentals', 'DevOps Fundamentals', 'Master continuous integration, deployment, and infrastructure management', 'devops-fundamentals', '100xSystems', 'intermediate', 80, '{"prerequisites": ["system-design"], "articles": ["docker-containers", "ci-cd-pipelines", "infrastructure-as-code", "monitoring-basics"], "quiz_score": 80, "project": "deployment-pipeline"}', '/certificates/templates/devops-fundamentals.html', '/certificates/badges/devops-fundamentals.svg', true, 9),
('cloud-architecture', 'Cloud Architecture Mastery', 'Design and implement cloud-native solutions using modern cloud platforms', 'devops-cloud', '100xSystems', 'advanced', 100, '{"prerequisites": ["devops-fundamentals"], "articles": ["aws-fundamentals", "cloud-design-patterns", "serverless-architecture", "cost-optimization"], "quiz_score": 85, "project": "cloud-deployment"}', '/certificates/templates/cloud-architecture.html', '/certificates/badges/cloud-architecture.svg', true, 10),

-- AI & Machine Learning Certifications
('ai-fundamentals', 'AI Fundamentals', 'Understanding artificial intelligence concepts, machine learning basics, and practical applications', 'ai-fundamentals', '100xSystems', 'intermediate', 90, '{"prerequisites": ["foundation-javascript"], "articles": ["ml-basics", "neural-networks-intro", "data-preprocessing", "model-evaluation"], "quiz_score": 80, "project": "ml-model"}', '/certificates/templates/ai-fundamentals.html', '/certificates/badges/ai-fundamentals.svg', true, 11),
('prompt-engineering', 'Prompt Engineering Mastery', 'Master the art and science of effective prompt engineering for LLMs', 'ai-prompt-engineering', '100xSystems', 'intermediate', 60, '{"prerequisites": ["ai-fundamentals"], "articles": ["prompt-basics", "advanced-techniques", "fine-tuning-basics", "production-prompts"], "quiz_score": 85, "project": "prompt-library"}', '/certificates/templates/prompt-engineering.html', '/certificates/badges/prompt-engineering.svg', true, 12),

-- Leadership Certifications
('technical-leadership', 'Technical Leadership', 'Develop skills to lead technical teams and make strategic technology decisions', 'leadership-technical', '100xSystems', 'advanced', 80, '{"prerequisites": ["fullstack-development", "system-design"], "articles": ["team-management", "technical-strategy", "code-review-leadership", "mentoring-skills"], "quiz_score": 80, "project": "leadership-portfolio"}', '/certificates/templates/technical-leadership.html', '/certificates/badges/technical-leadership.svg', true, 13),
('engineering-judgment', 'Engineering Judgment', 'Cultivate the ability to make sound technical decisions and evaluate technologies', 'leadership-judgment', '100xSystems', 'advanced', 60, '{"prerequisites": ["technical-leadership"], "articles": ["technology-evaluation", "architectural-decisions", "risk-assessment", "innovation-management"], "quiz_score": 85, "project": "decision-framework"}', '/certificates/templates/engineering-judgment.html', '/certificates/badges/engineering-judgment.svg', true, 14),

-- Specialized Certifications
('mobile-development', 'Mobile Development', 'Build native and cross-platform mobile applications', 'development-mobile', '100xSystems', 'intermediate', 70, '{"prerequisites": ["frontend-development"], "articles": ["react-native-basics", "mobile-ui-design", "app-store-deployment", "mobile-performance"], "quiz_score": 80, "project": "mobile-app"}', '/certificates/templates/mobile-development.html', '/certificates/badges/mobile-development.svg', true, 15),
('performance-optimization', 'Performance Optimization', 'Master techniques for optimizing application performance and user experience', 'systems-performance', '100xSystems', 'advanced', 80, '{"prerequisites": ["fullstack-development"], "articles": ["frontend-optimization", "backend-performance", "database-tuning", "monitoring-analytics"], "quiz_score": 85, "project": "performance-audit"}', '/certificates/templates/performance-optimization.html', '/certificates/badges/performance-optimization.svg', true, 16),

-- Mastery Certifications
('100x-engineer', '100x Engineer Certification', 'The ultimate certification demonstrating mastery across all domains of software engineering', 'mastery-100x', '100xSystems', 'advanced', 200, '{"prerequisites": ["technical-leadership", "engineering-judgment", "cloud-architecture"], "articles": ["comprehensive-review", "capstone-project", "peer-mentoring", "knowledge-sharing"], "quiz_score": 90, "project": "100x-portfolio", "essays": ["engineering-philosophy", "future-trends"]}', '/certificates/templates/100x-engineer.html', '/certificates/badges/100x-engineer.svg', true, 17);

-- Add comments for documentation
COMMENT ON TABLE certifications IS 'Comprehensive certification programs covering all aspects of software engineering';
COMMENT ON COLUMN certifications.requirements IS 'JSON object with articles, projects, quizzes, and other requirements';
COMMENT ON COLUMN certifications.estimated_hours IS 'Estimated time to complete certification including all requirements';
COMMENT ON COLUMN certifications.validity_months IS 'Certificate validity period, null for lifetime certification';
