import type { Meta, StoryObj } from '@storybook/react';
import { Button, Input, Textarea, Badge, Tag, Spinner, Card, CardHeader, Select, Toggle, ProgressBar, Skeleton, SkeletonBlock, Modal, Heading, Text, Divider } from '../components.atomic';

const meta = {
  title: 'Atoms/All',
  component: Button,
  parameters: { layout: 'fullscreen' },
  tags: ['autodocs'],
  decorators: [(Story) => <div style={{ padding: '3rem 1.5rem', maxWidth: '800px' }}><Story /></div>],
} satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const ButtonStory: Story = { name: 'Button', render: () => <div className="flex flex-col gap-6 p-4"><div className="flex flex-wrap items-center gap-4"><Button variant="primary">Primary</Button><Button variant="primary" loading>Loading</Button><Button variant="primary" icon={<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7"/></svg>}>With Icon</Button></div><div className="flex flex-wrap items-center gap-4"><Button variant="ghost">Ghost</Button><Button variant="ghost" icon={<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/></svg>}>Ghost with Icon</Button></div><div className="flex flex-wrap items-center gap-4"><Button variant="ripple">Ripple</Button><Button variant="ripple" loading>Loading</Button><Button variant="ripple" icon={<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10"/></svg>}>Ripple with Icon</Button></div></div> };
export const InputStory: Story = { name: 'Input', render: () => <div className="flex flex-col gap-8 max-w-md"><Input label="Email" placeholder="you@example.com" /><Input label="Password" type="password" placeholder="••••••••" helperText="Min 8 characters" /><Input label="Search" placeholder="Search..." leftIcon={<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" /></svg>} /><Input label="With Error" defaultValue="wrong@" errorMessage="Invalid email address" /></div> };
export const TextareaStory: Story = { name: 'Textarea', render: () => <div className="flex flex-col gap-8 max-w-md"><Textarea label="Bio" placeholder="Tell us about yourself..." helperText="Max 500 characters" /><Textarea label="Message" placeholder="Write your message..." defaultValue="Hello, I'm interested in..." rows={3} /><Textarea label="With Error" defaultValue="This content is too short" errorMessage="Minimum 50 characters required" /></div> };
export const BadgeStory: Story = { name: 'Badge', render: () => <div className="flex flex-col gap-4"><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Colors:</p><div className="flex flex-wrap gap-3"><Badge variant="purple">Purple</Badge><Badge variant="yellow">Yellow</Badge><Badge variant="black">Black</Badge></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">With dot:</p><div className="flex flex-wrap gap-3"><Badge variant="purple" dot>Live</Badge><Badge variant="yellow" dot>Featured</Badge><Badge variant="black" dot>New</Badge></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Sizes:</p><div className="flex flex-wrap items-center gap-3"><Badge variant="purple" size="sm">Small</Badge><Badge variant="purple">Default</Badge><Badge variant="purple" size="lg">Large</Badge></div></div> };
export const CardStory: Story = { name: 'Card', render: () => <Card header={<CardHeader title="Hello" subtitle="World" />} footer={<Button size="sm">Action</Button>}>Body content</Card> };
export const SpinnerStory: Story = { name: 'Spinner', render: () => <div className="flex flex-col gap-6"><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Sizes:</p><div className="flex flex-wrap items-center gap-5"><Spinner size="xs" /><Spinner size="sm" /><Spinner /><Spinner size="lg" /><Spinner size="xl" /></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">In context (button):</p><div className="flex items-center gap-3"><Spinner size="xs" /><span className="text-sm text-fg-secondary">Loading...</span></div></div> };
export const TagStory: Story = { name: 'Tag', render: () => <div className="flex flex-col gap-6"><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Variants:</p><div className="flex flex-wrap gap-3"><Tag variant="default">Assist</Tag><Tag variant="brand">React</Tag><Tag variant="success">Featured</Tag><Tag variant="outline">Suggestion</Tag></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">With leading icon:</p><div className="flex flex-wrap gap-3"><Tag variant="brand" leadingIcon={<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/></svg>}>Settings</Tag><Tag variant="outline" leadingIcon={<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/></svg>}>Explore</Tag></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Removable (Input chips):</p><div className="flex flex-wrap gap-3"><Tag variant="brand" size="sm" removable onRemove={() => {}}>React</Tag><Tag variant="success" size="sm" removable onRemove={() => {}}>TypeScript</Tag><Tag variant="default" size="sm" removable onRemove={() => {}}>Next.js</Tag></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Clickable / Filter:</p><div className="flex flex-wrap gap-3"><Tag variant="default" onClick={() => {}} className="cursor-pointer">All</Tag><Tag variant="brand" onClick={() => {}}>Active</Tag><Tag variant="outline" onClick={() => {}}>Archived</Tag></div></div> };
export const SelectStory: Story = { name: 'Select', render: () => <div className="flex flex-col gap-8 max-w-md"><Select label="Difficulty" options={[{ value: 'beginner', label: 'Beginner' }, { value: 'intermediate', label: 'Intermediate' }, { value: 'advanced', label: 'Advanced' }]} /><Select label="Status" placeholder="Select status..." options={[{ value: 'active', label: 'Active' }, { value: 'inactive', label: 'Inactive' }, { value: 'pending', label: 'Pending' }]} /><Select label="With Error" options={[{ value: 'opt1', label: 'Option 1' }]} errorMessage="Please select an option" /></div> };
export const ToggleStory: Story = { name: 'Toggle', render: () => <div className="flex flex-col gap-4"><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">States:</p><div className="flex flex-col gap-4"><Toggle checked={true} onChange={() => {}} label="Notifications" /><Toggle checked={false} onChange={() => {}} label="Dark Mode" /><Toggle checked={false} onChange={() => {}} label="Disabled" disabled /><Toggle checked={true} onChange={() => {}} label="Small" size="sm" /></div></div> };
export const ProgressBarStory: Story = { name: 'ProgressBar', render: () => <div className="flex flex-col gap-6"><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Determinate:</p><div className="flex flex-col gap-4"><ProgressBar value={45} /><ProgressBar value={72} showLabel /><ProgressBar value={30} size="lg" showLabel /></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Indeterminate:</p><ProgressBar /></div> };
export const SkeletonStory: Story = { name: 'Skeleton', render: () => <div className="flex flex-col gap-6"><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Individual:</p><div className="flex flex-col gap-2 max-w-md"><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-3/4" /><Skeleton className="h-4 w-1/2" /></div><p className="text-xs text-fg-muted uppercase tracking-wider font-semibold">Block (card skeleton):</p><SkeletonBlock lines={3} /></div> };
export const ModalStory: Story = { name: 'Modal', render: () => <Modal isOpen={true} onClose={() => {}} title="Modal Title">Modal content</Modal> };

export const TypographyStory: Story = { name: 'Typography', render: () => <div><Heading variant="h1">Heading 1</Heading><Text variant="body">Body text</Text><Divider /><Text variant="caption">Caption</Text></div> };
